name:                kite
version:             0.1.0.0
github:              "hmac/kite"
license:             BSD3
author:              "Harry Maclean"
maintainer:          "harry@hmac.dev"
copyright:           "2019 Harry Maclean"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A Haskell-like language for scripting and web apps
category:            compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  Kite is a statically typed, strict, purely functional programming language with full type inference.
  It's the core parts of Haskell with better ergonomics, an interpreter, native JS
  support and much better tooling.

  Kite targets the Ruby use case: web applications and scripts. For teams building big
  Rails apps that are struggling with stability and productivity as their codebase
  grows, Kite should provide a compelling alternative.

default-extensions:
- OverloadedStrings
- LambdaCase
- TupleSections
- DeriveDataTypeable
- Rank2Types
- TemplateHaskell

dependencies:
- base >= 4.7 && < 5
- extra
- text
- megaparsec
- prettyprinter
- prettyprinter-ansi-terminal
- pretty-simple
- containers
- transformers
- mtl
- optparse-generic
- semigroupoids
- directory
- hedgehog
- dhall

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  kite:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kite
    - pretty-simple
  kite-profiling:
    main: Main.hs
    source-dirs:         app
    ghc-options: -O2 -threaded -fprof-auto "-with-rtsopts=-N -p -s -h -i0.1"
    dependencies:
    - kite
  kite-bench:
    source-dirs: benchmarks
    main: Main.hs
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kite
    - criterion
    - filepath
    - extra

tests:
  kite-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kite
    - QuickCheck
    - hspec
    - hspec-megaparsec
    - hedgehog
    - hspec-hedgehog
    - filepath
    - template-haskell
  kite-hlint:
    main: hlint.hs
    other-modules: []
    source-dirs:
    - test
    - src
    dependencies:
    - kite
    - hlint
