name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: kite
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -A kite
    - run: $(nix-build -A haskellPackages.brittany)/bin/brittany -c src/**/*.hs app/**/*.hs test/**/*.hs benchmarks/**/*.hs
