name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: kite
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -A kite
    - run: nix-shell --command "find src app test benchmarks -name '*.hs' | xargs brittany -c"
